README.md
resources/swiftlint.yml

Closes https://github.com/airbnb/swift/issues/72 by attaching the appropriate [SwiftLint rule](https://github.com/realm/SwiftLint/blob/master/Rules.md#unused_optional_binding) to our `optional-nil-check` rule. 

Add SwiftLint rule for `optional-nil-check`

---

README.md

Replaced SwiftFormat README links with direct links to the rules documentation.
Self-explanatory.

Add direct links to SwiftFormat rule docs

---

README.md

Replaced the links to the SwiftLint `control_statement`, `empty_parentheses_with_trailing_closure` and `unneeded_parentheses_in_closure_argument` rules with the SwiftFormat `redundantParens` rule.
One rule seems easier to manage than three, and SwiftLint doesn't currently have an autofix for the `control_statement` rule, whereas SwiftFormat's `redundantParens` rule fixes all of the unnecessary parens scenarios listed in the style guide.

Add link to SwiftFormat’s redundantParens rule

---

resources/airbnb.swiftformat

I forgot about requiring this after [this PR](https://github.com/airbnb/swift/pull/77)

Add redundantParens to airbnb.swiftformat

---

README.md
resources/airbnb.swiftformat

Added link to SwiftFormat rule for removing implicit self.
SwiftFormat is able to reliably remove all redundant uses of `self` automatically (SwiftLint can automatically insert `self`, but not remove it).

Add link to SwiftFormat’s redundantSelf rule

---

README.md

Removed the guideline about `where`-clause positioning in `switch` statements.
Swift already generates a warning for this scenario (see screenshot), so mentioning it seems redundant (on the assumption that "code should compile with no warnings" is already an implicit guideline).

Remove redundant guideline

---

resources/swiftlint.yml

Removing unused SwiftLint rules after https://github.com/airbnb/swift/pull/77 got merged

Remove now unused SwiftLint rules

---

README.md
resources/swiftlint.yml

Remove the closure_end_indentation rule
It violates the second guiding tenet of the style guide:
> These rules should not fight Xcode's ^ + I indentation behavior.
I understand that many people dislike Xcode's default style of indenting closure end braces, but I think the guiding tenet is more important. This exception will negatively impact programmer experience and productivity by guaranteeing a locally inconsistent style and linting failure every time Xcode autocompletes a block or we use ^+I.  
The "don't fight Xcode" tenet is important to me because it, in turn, reflects a much broader tenet: "do no harm". It's an assurance that the goal of the style guide is to assist and supplement our other tools to improve the clarity and consistency of code -- not to impose rules even if there …

Remove closure_end_indentation rule

---

README.md

Since space fleet is two words, the class name used in this example should have the correct casing to reflect that. `Spacefleet` -> `SpaceFleet`.
Our examples should follow Apple's guidelines of using `UpperCamelCase` for type names.

Fix capitalization of "Spacefleet" in README

---

resources/swiftlint.yml

This will add custom_rules to the whitlist, otherwise they won´t get applied.
If using custom rules alongside a whitelist, make sure to add custom_rules as an item under whitelist_rules. See also [SwiftLint README](https://github.com/realm/SwiftLint/blob/master/README.md#defining-custom-rules)

Add custom_rules to whitelist

---

README.md

Updated Function Name in Example
Example should conform to previous rule: "Event-handling functions should be named like past-tense sentences"

Adjust Example

---

README.md

I believe the intention of this guard was to guard against an empty string for the assertionFailure.
This is pretty small but hopefully clarifies the intention of the guard given the comment above it.
As the code is written, this would actually have the opposite effect and alway call the assertionFailure.  I think its minor but I just saw it while reading through the rules.

Clarify detail example for guard in preconditions-and-asserts

---

.gitattributes

Currently, GitHub incorrectly displays this repository as being a Shell project:
This PR adds a `.gitattributes` file so that GitHub will consider Markdown files when making its language determination for this repository:
This is a similar change to what I proposed on Swift Evolution (https://github.com/apple/swift-evolution/pull/1074), and much of the same rationale applies here as well. The basic gist is that correcting this categorization will help discoverability and encourage new contributions.  

Consider Markdown for Repository Language Determination

---

README.md

- Removes `func isURLReachable(_:)`. IMHO this function was adding minimal educational value. The only difference between `func isURLReachable(_:)` and `isValidURL(_:)` is that "URL" is in the middle instead of the end. I don't think this is very debateable, and so I think we should simplify to focus on more interesting cases.
- The line of code `let urlValidator = URLValidator().isValidURL(/* some URL */)` doesn't make sense. We're creating a variable called `urlValidator` that is actually a `Bool` 🤦‍♂ The `urlValidator` variable now has semantic meaning.
- Adds examples that show how we recommend formatting "ID".
Apple's [`Identifiable` protocol](https://developer.apple.com/documentation/swift/identifiable) establishes that `ID` is [uppercase when used as a …

Add "ID" example capitalize-acronyms rule, and make example more powerful

---

README.md

Starting in Swift 4.2 (released September 2018), `self` is allowed to be upgraded from a weak reference to strong reference: [Allow using optional binding to upgrade self from a weak to strong reference](https://github.com/apple/swift-evolution/blob/master/proposals/0079-upgrade-self-from-weak-to-strong.md)
I propose that we adopt this style for the same reasons it was accepted into Swift language.
* Avoid having to deal with `strongSelf`, `s`, `ss`
* Follows existing Swift convention of optional binding that reuses the name of the variable.

Add style for upgrading weak self to strong reference

---

README.md
resources/airbnb.swiftformat

I propose we adopt a new `omit-return` rule:
> **Omit the `return` keyword when not required by the language.** 
> **[[SwiftFormat: redundantReturn]](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#redundantReturn)**
```swift
// WRONG
["1", "2", "3"].compactMap { return Int($0) }
var size: CGSize {
return CGSize(
width: 100.0,
height: 100.0)
}
func makeInfoAlert(message: String) -> UIAlertController {
return UIAlertController(
title: "ℹ️ Info",
message: message,
preferredStyle: .alert)
}
// RIGHT
["1", "2", "3"].compactMap { Int($0) }
var size: CGSize {
CGSize(
width: 100.0,
height: 100.0)
}
func makeInfoAlert(message: String) -> UIAlertController {
UIAlertController(
title: "ℹ️ Info",
message: message,
preferredStyle: .alert)
}
```
- As of Swift 5.1 …

Add omit-return rule

---

README.md

Hello old friends! I found a thing I don't like in the complex closure example, so I fixed it
As it is, the `RIGHT` example violates the unused closure parameter rule. Just adding `response` as a parameter to `doSomething` to make things more clear.

Update complex closure example

---

README.md
resources/airbnb.swiftformat
resources/swiftlint.yml

https://github.com/airbnb/swift/issues/97
Use `: AnyObject` instead of `: class` in protocol definitions
[This accepted Swift proposal](https://github.com/apple/swift-evolution/blob/master/proposals/0156-subclass-existentials.md#class-and-anyobject) that merges the concepts of `class` and `AnyObject` states that
> we suggest only keeping AnyObject around
We should update the guide to align with this evolution of Swift.
Popular linters such as Swift format and Swift lint already have rules for this:
https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#anyobjectprotocol
https://github.com/realm/SwiftLint/tree/master/Source/SwiftLintFramework/Rules/Lint

Prefer AnyObject over class in protocol definitions

---

README.md

It looks like we need an extra line of whitespace for GitHub to render this rule's markdown correctly.

Patch use-anyobject markdown formatting

---

README.md
resources/airbnb.swiftformat

This PR reintroduces several of our old wrapping rules:
- [Separate long function declarations with line breaks before each argument label and before the return signature](https://github.com/airbnb/swift/issues/38)
- [Long function invocations should also break on each argument](https://github.com/airbnb/swift/issues/40)
- [Multi-line arrays should have each bracket on a separate line](https://github.com/airbnb/swift/issues/42)
- [Place function/type attributes on the line above the declaration](https://github.com/airbnb/swift/issues/46)
We removed these rules because they were missing autocorrect, but they are fully supported by SwiftFormat in `0.45.1`.

Reintroduce old wrapping rules

---

README.md
resources/airbnb.swiftformat

This is a PR reintroduces several of our old file organization rules:
- [Use // MARK: to separate the contents of a type definition](https://github.com/airbnb/swift/issues/56)
- [Within each top-level section, place content in the following order](https://github.com/airbnb/swift/issues/60)
- [Computed properties and properties with property observers should appear at the end of the set of declarations of the same kind ](https://github.com/airbnb/swift/issues/64)
- [Add empty lines between property declarations of different kinds](https://github.com/airbnb/swift/issues/62)
We removed these rules because they were missing autocorrect, but they are now supported by SwiftFormat `0.46`'s new `organizeDeclarations` rule (nicklockwood/SwiftFormat#701).
I made a few small tweaks to the previous …

Reintroduce old file organization rules

---

README.md

Follow-up to https://github.com/airbnb/swift/pull/102#discussion_r479558324.
Starting in SwiftFormat `0.46.1` (nicklockwood/SwiftFormat#724), `typealias` declarations are grouped with nested types. We should state this explicitly in the rule description.

Explicitly mention typealiases in the subsection organization rule

---

README.md

This PR proposes removing this rule from our style guide:
> **Prefer putting constants in the top level of a file if they are `private`.** If they are `public` or `internal`, define them as static properties, for namespacing purposes.
> 
>   ```swift
>   private let privateValue = "secret"
>
>   public class MyClass {
>
>     public static let publicValue = "something"
>
>     func doSomething() {
>       print(privateValue)
>       print(MyClass.publicValue)
>     }
>
>   }
>   ```
Instead, I think we should recommend placing these constants in `enum` namespaces (as an extension to the existing [namespace-using-enums](https://github.com/airbnb/swift#namespace-using-enums) rule).
1. I don't think we should be suggesting that folks create top-level declarations. This feels at-odds with the …

Remove "Prefer putting constants in the top level of a file if they are private" rule

---

README.md
resources/airbnb.swiftformat

This PR updates `airbnb.swiftformat` to reflect that we now use SwiftFormat `0.47.4`, and updates the description of the `mark-types-and-extensions` to reflect the [updated behavior](https://github.com/nicklockwood/SwiftFormat/pull/802) of the `markTypes` rule.

Update to SwiftFormat 0.47.4

---

README.md
resources/airbnb.swiftformat

Remove redundant import statements within a file. [![SwiftFormat: duplicateImports](https://img.shields.io/badge/SwiftFormat-duplicateImports-7B0051.svg)](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#duplicateImports)
```swift
//WRONG
import Foundation
import Foundation
//RIGHT
import Foundation
```
Duplicated import statements have no effect and should be removed for clarity.

Deduplicate import statements within a file

---

resources/airbnb.swiftformat

This PR adds the `--wrapreturntype if-multiline` SwiftFormat option (added in [nicklockwood/SwiftFormat#764](https://github.com/nicklockwood/SwiftFormat/pull/764)) to `airbnb.swiftformat`.
This adds linter enforcement for an [existing rule](https://github.com/airbnb/swift#long-function-declaration) in our style guide:
> Separate long function declarations with line breaks before each argument label ***and before the return signature***. Put the open curly brace on the next line so the first executable line doesn't look like it's another parameter.
This rule is already described in our style guide -- we previously just weren't enforcing it through a linter.

Add --wrapreturntype if-multiline to airbnb.swiftformat

---

resources/airbnb.swiftformat

This PR updates `airbnb.swiftformat` to show that we are now using SwiftFormat `0.47.12` internally.

Bump SwiftFormat to 0.47.12

---

README.md

* Fix "capitalize-acronyms" example
* Add missing parentheses in 'use-camel-case' example
The reasoning explanation is not necessary. It's just a bug/typo fix.

Adjust example code to the described rule.

---

README.md
resources/swiftlint.yml

**Prefer dedicated logging systems like [`os_log`](https://developer.apple.com/documentation/os/logging) or [`swift-log`](https://github.com/apple/swift-log) over writing directly to standard out using `print(…)`, `logDebug(…)`, or `dump(…)`.**
Additionally includes a custom SwiftLint regex rule to flag violations as warnings. This rule isn't possible to autocorrect in the general case as the correct logging method depends on the specific app.
All log messages should flow into intermediary logging systems that can direct them to the correct destination(s) based on the app's environment or configuration. `print(…)`, `debugPrint(…)`, or `dump(…)` will write directly to standard out in all app configurations and can potentially leak personally identifiable information (PII).
_Please react …

Add "No direct standard out" rule

---

README.md

**Prefer immutable or computed static properties over mutable ones whenever possible.** Use stored `static let` properties or computed `static var` properties over stored `static var`s properties whenever possible, as stored `static var` properties are global mutable state.
Global mutable state increases complexity and makes it harder to reason about the behavior of applications. It should be avoided when possible.
```swift
// WRONG
enum Fonts {
static var title = UIFont(…)
}
// RIGHT
enum Fonts {
static let title = UIFont(…)
}
```
```swift
// WRONG
struct FeatureState {
var count: Int
static var initial = FeatureState(count: 0)
}
// RIGHT
struct FeatureState {
var count: Int
static var initial: FeatureState {
// Vend static properties that are cheap to compute
FeatureState(count: 0)
}
} …
```

Add "prefer immutable statics" rule

---

README.md
resources/airbnb.swiftformat

This PR enables the [`redundantType`](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#redundantType) SwiftFormat rule. This enforces the _"Don't include types where they can be easily inferred."_ rule [in our style guide](https://github.com/airbnb/swift#use-implicit-types).

Adopt redundantType SwiftFormat rule

---

resources/airbnb.swiftformat

We are now using SwiftFormat `0.48.0` at Airbnb

Bump SwiftFormat version to 0.48.0

---

README.md
resources/airbnb.swiftformat

This PR adopts SwiftFormat's `consecutiveSpaces` rule, piggybacking on top of the existing `limit-vertical-whitespace` rule
> **Limit consecutive whitespace to one blank line or space (excluding indentation).** Favor the following formatting guidelines over whitespace of varying heights to divide files into logical groupings.
```swift
// WRONG
struct Planet {
let mass:          Double
let hasAtmosphere: Bool
func travelTo() { }
}
// RIGHT
struct Planet {
let mass: Double
let hasAtmosphere: Bool
func travelTo() { }
}
```
This aligns with the style folks are currently using, based on my experience. Linting for this will prevent folks from unintentionally introducing stray whitespace.

Adopt consecutiveSpaces rule

---

README.md
resources/airbnb.swiftformat

This PR proposes a new rule to always inline the `let` keyword when destructuring enum cases and tupes
> When destructuring an enum case or a tuple, place the `let` keyword inline, adjacent to each individual property assignment
```swift
// WRONG
switch result {
case let .success(value):
// ...
case let .error(errorCode, errorReason):
// ...
}
// WRONG
guard let case .success(value) else { 
return 
}
// RIGHT
switch result {
case .success(let value):
// ...
case .error(let errorCode, let errorReason):
// ...
}
// RIGHT
guard case .success(let value) else {
return
}
```
1. **Consistency**: We should prefer to either _always_ inline the `let` keyworkd or _never_ inline the `let` keyword. In Airbnb's Swift codebase, we [observed](https://github.com/airbnb/swift/pull/126#discussion_r631979244) …

Add rule to always inline let keyword when destructuring enum cases and tuples

---

README.md
resources/airbnb.swiftformat

This PR proposes a rule to prefer the shorthand "sugared" form for common standard library types (`Optional`, `Array`, and `Dictionary`)
> **For standard library types with a canonical shorthand form (`Optional`, `Array`, `Dictionary`), prefer using the shorthand form over the full generic form.**
```swift
// WRONG
let optional: Optional<String> = nil
let array: Array<String> = []
let dictionary: Dictionary<String, Any> = [:]
// RIGHT
let optional: String? = nil
let array: [String] = []
let dictionary: [String: Any] = [:]
```
This aligns with what most folks already do in practice. 

Add rule to prefer shorthand form for Optional, Array, and Dictionary

---

README.md

In #127, I accidentally left out the closing `**`.

Fix markdown formatting in standard-library-type-shorthand rule

---

README.md
resources/airbnb.swiftformat
resources/xcode_settings.bash

This PR enables the SwiftFormat [`wrap`](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#wrap) rule in `airbnb.swiftformat`. We would begin enforcing a maximum line width of _130 characters_, and automatically wrap code to sit within the max line width. We would continue _recommending_ (but not enforcing) a maximum line width of 100 characters.
We should begin enforcing our maximum column width rule with a linter (_"We strive to make every rule lintable"_).
SwiftFormat's `wrap` rule is not perfect, but it follows our style guide / existing informal style preferences a large majority of the time (in general, it is more successful at wrapping longer lines). 100 characters seems [too strict](https://github.com/airbnb/swift/pull/132#issuecomment-905693965) to enforce with the …

Enable SwiftFormat wrap rule with an enforced max width of 130 characters

---

README.md
resources/airbnb.swiftformat

**Declarations that include scopes spanning multiple lines should be separated from adjacent declarations in the same scope by a newline.** Insert a single blank line between multi-line scoped declarations (e.g. types, extensions, functions, computed properties, etc.) and other declarations at the same indentation level.
```swift
// WRONG
struct SolarSystem {
var numberOfPlanets: Int {
…
}
func distance(to: SolarSystem) -> AstronomicalUnit {
…
}
}
struct Galaxy {
func distance(to: Galaxy) -> AstronomicalUnit {
…
}
func contains(_ solarSystem: SolarSystem) -> Bool {
…
}
}
// RIGHT
struct SolarSystem {
var numberOfPlanets: Int {
…
}
func distance(to: SolarSystem) -> AstronomicalUnit {
…
}
}
struct Galaxy {
func distance(to: Galaxy) -> AstronomicalUnit {
…
}
func contains(_ solarSystem: …
```

Add Newline Between Scope Siblings Rule

---

README.md
resources/airbnb.swiftformat

This PR adds a rule for how to indent long ternary operator expressions, using the new `--wrapternary before-operators` option added to SwiftFormat in https://github.com/nicklockwood/SwiftFormat/pull/1048.
> **[Long](https://github.com/airbnb/swift#column-width) ternary operator expressions should wrap before the `?` and before the `:`**, putting each conditional branch on a separate line.
```swift
// WRONG (too long)
let destinationPlanet = solarSystem.hasPlanetsInHabitableZone ? solarSystem.planetsInHabitableZone.first : solarSystem.uninhabitablePlanets.first
// WRONG (naive wrapping)
let destinationPlanet = solarSystem.hasPlanetsInHabitableZone ? solarSystem.planetsInHabitableZone.first :
solarSystem.uninhabitablePlanets.first
// WRONG (unbalanced operators)
let destinationPlanet = …
```

Add rule for how to wrap long ternary operator expressions

---

README.md
resources/airbnb.swiftformat

This PR adds a rule for how to indent multiline string literals, using the new `--indentstrings true` option added to SwiftFormat in https://github.com/nicklockwood/SwiftFormat/pull/1049
> **Indent the body of multi-line string literals**, unless the string literal begins on its own line.
```swift
// WRONG
var spaceQuote = """
“Space,” it says, “is big. Really big. You just won’t believe how vastly, hugely, mindbogglingly big it is.
I mean, you may think it’s a long way down the road to the chemist’s, but that’s just peanuts to space.”
"""
// RIGHT
var spaceQuote = """
“Space,” it says, “is big. Really big. You just won’t believe how vastly, hugely, mindbogglingly big it is.
I mean, you may think it’s a long way down the road to the chemist’s, but that’s just peanuts to space.”
"""
// …
```

Add rule for how to indent multiline string literals

---

resources/airbnb.swiftformat

This PR updates `airbnb.swiftformat` to reflect that we have enabled the `sortDeclarations` rule, added in https://github.com/nicklockwood/SwiftFormat/pull/1068. 
By itself, enabling this rule has no effect. This rule just must be enabled for the new `// swiftformat:sort` directives to work, since that support is implemented in this rule.

Update airbnb.swiftformat to reflect that we have enabled the sortDeclarations rule

---

README.md
resources/airbnb.swiftformat

This PR proposes a new rule that the opening brace following a single-line statement should be on the same line as the statement itself:
```swift
// WRONG
if !planet.isHabitable
{
planet.terraform()
}
class Planet
{
func terraform()
{
generateAtmosphere()
generateOceans()
}
}
// RIGHT
if !planet.isHabitable {
planet.terraform()
}
class Planet {
func terraform() {
generateAtmosphere()
generateOceans()
}
}
```
This PR also adds a prose rule for the multi-line case:
> The opening brace following a multi-line statement should wrap to a new line.
It felt like a good idea to add an explicit prose rule for this, to compliment the new rule for the single-statement case. This specific style is already mentioned in other rules, and we already lint for this automatically using the …

Add rule that the opening brace following a single-line statement should be on the same line as the statement itself

---

README.md
resources/airbnb.swiftformat
resources/swiftlint.yml

The PR adopts the SwiftFormat `redundantPattern` rule, instead of the SwiftLint `empty_enum_arguments` rule. 
Both of these rule implementations cover our existing [unnecessary-enum-arguments](https://github.com/airbnb/swift#unnecessary-enum-arguments) rule, but I noticed that the SwiftLint implementation misses some examples that the SwiftFormat implementation autocorrects properly.

Use SwiftFormat redundantPattern rule instead of SwiftLint empty_enum_arguments rule

---

README.md
resources/airbnb.swiftformat
resources/swiftlint.yml

This PR adds a new rule to omit `Void` return types from closure definitions. 
```swift
// WRONG
someAsyncThing() { argument -> Void in
...
}
// RIGHT
someAsyncThing() { argument in
...
}
```
This was previously present in our style guide, but was removed because it was missing autocorrect (Fixes #50). As of nicklockwood/SwiftFormat#1056, this is the default behavior of the SwiftFormat `redundantVoidReturnType` rule.
This also follows pretty naturally from the [existing rule](https://github.com/airbnb/swift#omit-function-void-return) that says to omit `Void` return types from function definitions.

Add rule to omit Void return types from closure definitions

---

README.md
resources/airbnb.swiftformat
resources/swiftlint.yml

This PR adds a new rule that braces should be surrounded by whitespace (either a space or newline):
```swift
// WRONG
struct Planet{
…
}
// WRONG
if condition{
…
}else{
…
}
// RIGHT
struct Planet {
…
}
// RIGHT
if condition {
…
} else {
…
}
```
<a id='closure-brace-spacing'></a>(<a href='#closure-brace-spacing'>link</a>) This PR also updates the existing rule for how to handle closure braces (which is sightly more nuanced):
> **Closures should have a space or newline inside each brace.** Trailing closures should have a space or newline outside each brace.
```swift
// WRONG
let evenSquares = numbers.filter{$0.isMultiple(of: 2)}.map{  $0 * $0  }
// RIGHT
let evenSquares = numbers.filter { $0.isMultiple(of: 2) }.map { $0 * $0 }
// WRONG
let evenSquares = numbers.filter( { $0.isMultiple(of: …
```

Add rule that braces should be surrounded by whitespace (either a space or newline)

---

resources/airbnb.swiftformat

This PR updates the `--swiftversion` in `airbnb.swiftformat` from 5.1 to 5.5, to reflect that we are now using Swift 5.5 at Airbnb.

Bump SwiftFormat --swiftversion from 5.1 to 5.5

---

README.md
resources/airbnb.swiftformat

This PR enables the [`redundantFileprivate`](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#redundantFileprivate) SwiftFormat rule.
We already have a prose rule for this in the style guide ([_"Access control should be at the strictest level possible: prefer `private` to `fileprivate`"_](https://github.com/airbnb/swift#limit-access-control)), so this just adds autocorrect.

Adopt redundantFileprivate SwiftFormat rule

---

README.md
resources/swiftlint.yml

This PR removes references to the `type-names` SwiftLint rule, which we don't use internally since it doesn't support autocorrect. This resolves #93.

Remove reference to type-names SwiftLint rule

---

README.md
resources/airbnb.swiftformat
resources/swiftlint.yml

This PR removes the SwiftLint [`redundant_string_enum_value`](https://realm.github.io/SwiftLint/redundant_string_enum_value.html) rule (which doesn't support autocorrect) in favor of the SwiftFormat [`redundantRawValues`](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#redundantrawvalues) rule (which does support autocorrect).

Use SwiftFormat redundantRawValues instead of SwiftLint redundant_string_enum_value

---

README.md
resources/airbnb.swiftformat

This PR adds a new rule to omit the `get` clause from computed property declarations that don't also have a `set`, `willSet`, or `didSet` clause.
```swift
// WRONG
var universe: Universe {
get {
Universe()
}
}
// RIGHT
var universe: Universe {
Universe() 
}
// RIGHT
var universe: Universe {
get { multiverseService.current }
set { multiverseService.current = newValue }
}
```
A standalone `get { }` clause is redundant and can be removed without affecting the behavior of the code.

Add rule to omit get clause from computed property declarations when unnecessary

---

README.md
resources/airbnb.swiftformat

This PR adds the [enumNamespaces SwiftFormat rule](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#enumnamespaces).
This aligns with [an existing prose rule](https://github.com/airbnb/swift#namespace-using-enums).

Add enumNamespaces SwiftFormat rule

---

resources/airbnb.swiftformat

This PR updates `airbnb.swiftformat` to reflect that we are now using [0.50-beta-1](https://github.com/calda/SwiftFormat/releases/tag/0.50-beta-1)

Update SwiftFormat version to 0.50-beta-1

---

README.md
resources/airbnb.swiftformat

This PR proposes a new rule that comment blocks should use single-line comments (`//` and `///`) rather than multi-line comments (`/* ... */` and `/** ... */`). This is implemented by SwiftFormat's [`blockComments`](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#blockComments) rule.
```swift
// WRONG
/**
* A planet that exists somewhere in the universe.
*
* Planets have many properties. For example, the best planets
* have atmospheres and bodies of water to support life.
*/
class Planet {
/**
Terraforms the planet, by adding an atmosphere and ocean
that is hospitable for life.
- Precondition: the planet does not already have an atmosphere.
Adding another atmosphere to a planet that already has one is a very bad idea.
*/
func terraform() {
/* 
Generate the atmosphere …
```

Add rule that comment blocks should use single-line comments (// and ///)

---

README.md

Fixes example code
Should be `redundantRawValues` instead of `redundantEnumValues`. 
https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#redundantRawValues

Fix redundantRawValues example

---

README.md
resources/airbnb.swiftformat

This PR adds a rule to include spaces before and after comments, implemented by the SwiftFormat [`spaceAroundComments`](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#spacearoundcomments) and [`spaceInsideComments`](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#spaceinsidecomments) rules.
> Include spaces before and after comments
```swift
// WRONG
///A spacecraft with incredible performance characteristics
struct Spaceship {
func travelFasterThanLight() {/*unimplemented*/}
func travelBackInTime() { }//TODO: research whether or not this is possible
}
// RIGHT
/// A spacecraft with incredible performance characteristics
struct Spaceship {
func travelFasterThanLight() { /* unimplemented */ }
func travelBackInTime() { } // TODO: research whether or not …
```

Add rule to include spaces before and after comment delimiters

---

README.md
resources/airbnb.swiftformat

This PR adds a new rule that there should be no spaces before or inside the parentheses of function calls / declarations. This is implemented by SwiftFormat's [`spaceAroundParens`](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#spacearoundparens) and [`spaceInsideParens`](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#spaceInsideParens) rules.
```swift
// WRONG
func install ( _ engine: Engine ) { }
install ( AntimatterDrive( ) )
// RIGHT
func install(_ engine: Engine) { }
install(AntimatterDrive())
```
Automatically-formatted spacing is good for consistency and legibility.

Add rule that there should be no spaces before or inside the parentheses of function calls / declarations

---

README.md
resources/airbnb.swiftformat

This PR proposes a new rule to use commas instead of `&&` operators in conditional statements.
```swift
// WRONG
if let star = planet.star, !planet.isHabitable && planet.isInHabitableZone(of: star) {
planet.terraform()
}
if
let star = planet.star, 
!planet.isHabitable 
&& planet.isInHabitableZone(of: star)
{
planet.terraform()
}
// RIGHT
if let star = planet.star, !planet.isHabitable, planet.isInHabitableZone(of: star) {
planet.terraform()
}
if
let star = planet.star,
!planet.isHabitable,
planet.isInHabitableZone(of: star)
{
planet.terraform()
}
```
This syntax is more idiomatic, and increases consistency when mixed with optional unwrapping conditions.

Use commas instead of `&&` operators in conditional statements

---

resources/xcode_settings.bash

This PR updates the `xcode_settings.sh` script to enable spell check in Xcode. It works really well (e.g. handles camel case properly), but isn't enabled by default for some reason.

Update xcode_settings.sh script to enable Xcode spell check

---

Package.resolved
Package.swift

I'm working on integrating the new format tool in the Epoxy repo (https://github.com/airbnb/epoxy-ios/pull/112) and am hitting a strange SwiftLint failure (`error: unknownError(exitCode: 10)`) that I can't reproduce locally.  I tested the most recent commit from SwiftLint's master branch and it didn't encounter that error, so it must have been fixed recently.

Bump SwiftLint version to fix strange failure in Epoxy repo

---

Plugins/FormatSwift/Plugin.swift
Sources/AirbnbSwiftFormatTool/AirbnbSwiftFormatTool.swift

This PR improves error handling for the format plugin, and adds support for an `--exclude` flag.
I'm adopting the plugin in the Lottie and Epoxy repos, and noticed that it was outputting a `lintFailure` even in cases where SwiftLint / SwiftFormat were failing due to reasons unrelated to the lint configuration. Now we clarify between an expected failure (a `lintFailure`) and an unknown / unexpected failure that we cannot recover from.
Epoxy specifically doesn't lint its `Tests` subdirectory, so we needed a way to configure the directories that are formatted / linted by the plugin. I figured we can use an `--exclude` flag for this, to compliment the exclude configurations in `airbnb.swiftformat` / `swiftlint.yml`.

Improve error handling, add support for `--exclude` flag

---

Plugins/FormatSwift/Plugin.swift

This adds a `--files` parameter to the Swift package plugin so that you can choose to _only_ format specific files that you wish rather than entire targets or packages.
In some situations it's useful to only format specific files. For example you might want to set up a pre-commit git hook to format _only_ staged swift files before committing them. 

Add files argument to only lint specific paths

---

README.md

This PR adds info about the new Swift Package Manager command plugin to the `README.md`.

Add info about Swift Package Manager command plugin to README.md

---

README.md

This PR adds Swift Package Index badges that link to our package's [SPI listing](https://swiftpackageindex.com/airbnb/swift). 
I figured we could specifically add them to the section that discusses the package plugin. Alternatively we could put them at the very top of the page under the title.

Add Swift Package Index badges

---

Package.swift

We view the `AirbnbSwiftFormatTool` as an implementation detail of our SPM plugin. Accordingly we are removing this tool as a "public" product of our SPM package.
One reason we made this choice is that the `AirbnbSwiftFormatTool` has an associated bundle that contains the config files for SwiftLint and SwiftFormat.
My understanding is that the associated bundle make this tool less portable, since we're by default looking for files in that bundle.
https://github.com/airbnb/swift/blob/1d8bb91f317a5f48be9a26e77558cae7398da385/Sources/AirbnbSwiftFormatTool/AirbnbSwiftFormatTool.swift#L34-L38
I made edits to the source code of the plugin that violated the style guide. Then I ran `swift package format` in the root of the repo and noticed that those violations were corrected.
@calda …

Remove `AirbnbSwiftFormatTool` as product

---

Plugins/FormatSwift/Plugin.swift
README.md
Sources/AirbnbSwiftFormatTool/AirbnbSwiftFormatTool.swift

This PR updates the package plugin to use the `swift-tools-version` specified in `Package.swift` as the minimum Swift version by default. This can also be customized manually by passing in a `--swift-version` option.
Previously the SwiftFormat `--swiftversion` was included in `airbnb.swiftformat` and was not overridable. We listed 5.6, but Lottie for example has a minimum supported Swift version of 5.3. To override the default `--swiftversion 5.6` option, I set up a `.swift-version` file at the repo root to specify `5.3`. This file is conflicting with Cocoapods (airbnb/lottie-ios#1672), so turned out to not be a good approach.

Use `swift-tools-version` from `Package.swift` as minimum Swift version by default

---

Plugins/FormatSwift/Plugin.swift
Sources/AirbnbSwiftFormatTool/AirbnbSwiftFormatTool.swift

This PR makes changes changes based on feedback from @bachand:
- Updated plugin to not pass multiple `--swift-format` arguments to underlying tool (https://github.com/airbnb/swift/pull/180#discussion_r932780947)
- Updated `XcodeCommandPlugin` to support `--exclude` arguments (https://github.com/airbnb/swift/pull/181#discussion_r932785998)

Improve handling of `--swift-format` and `--exclude` arguments

---

README.md

- Fixes a typo and example method's type annotations.
- "reqired" is definitely a typo.
- broken type annotations can be confusing to read.
cc. @calda @airbnb/swift-styleguide-maintainers

Fix typo and broken type annotations

---

Package.swift

This PR updates `Package.swift` to use a SwiftFormat build based on this week's 0.49.16 release: https://github.com/calda/SwiftFormat/releases/tag/0.50-beta-4

Update to SwiftFormat build based on 0.49.16

---

README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR proposes a new rule to prefer trailing closure syntax for closure arguments with no parameter name. This rule has autocomplete implemented by the SwiftFormat `trailingClosures` rule.
```swift
// WRONG
planets.map({ $0.name })
// RIGHT
planets.map { $0.name }
// ALSO RIGHT, since this closure has a parameter name
planets.first(where: { $0.isGasGiant })
// ALSO FINE. Trailing closure syntax is still permitted for closures
// with parameter names. However, consider using non-trailing syntax
// in cases where the parameter name is semantically meaningful.
planets.first { $0.isGasGiant }
```
For closure arguments with no parameter name, trailing closure syntax is more idiomatic and doesn't decrease expressivity or readability. 
_Please react with 👍/👎 if you agree or disagree with this …

Add rule to prefer trailing closure syntax for closure arguments with no parameter name

---

README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR proposes a new rule to prefer the shorthand `if let` optional unwrapping syntax added in Swift 5.7:
> Omit the right-hand side of the expression when unwrapping an optional property to a non-optional property with the same name.
```swift
// WRONG
if
let galaxy = galaxy,
galaxy.name == "Milky Way"
{ … }
guard
let galaxy = galaxy,
galaxy.name == "Milky Way"
else { … }
// RIGHT
if
let galaxy,
galaxy.name == "Milky Way"
{ … }
guard
let galaxy,
galaxy.name == "Milky Way"
else { … }
```
We are adopting Swift 5.7 soon, so we should adopt guidance for its new language features.
As discussed in the Motivation section of [SE-0345](https://github.com/apple/swift-evolution/blob/main/proposals/0345-if-let-shorthand.md), the new shorthand optional unwrapping syntax removes unnecessary …

Add rule to prefer shorthand `if let` optional unwrapping syntax

---

README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR proposes a new rule to prefer simplified generic extension syntax, using bracket syntax or sugared type syntax for applicable standard library types, instead of generic type constraints.
```swift
// WRONG
extension Array where Element == Star { … }
extension Optional where Wrapped == Spaceship { … }
extension Dictionary where Key == Moon, Element == Planet { … }
extension Collection where Element == Universe { … }
extension StateStore where State == SpaceshipState, Action == Spaceship { … }
// RIGHT
extension [Star] { … }
extension Spaceship? { … }
extension [Moon: Planet] { … }
extension Collection<Universe> { … }
extension StateStore<SpaceshipState, SpaceshipAction> { … }
```
We are adopting Swift 5.7 soon, so we should adopt guidance for its new language features.
This …

Add rule to prefer simplified generic extension syntax

---

README.md

- Fixed `Naming` exception example (underscore prefix) to match the parameter types with those of `private let` property.
- Fixed some typos.
- For better doc clarity.
cc. @calda

Fix Naming exception example (underscore prefix)

---

Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR proposes a rule to prefer opaque generic parameter syntax (using `some`) over the more-verbose named generic parameter syntax where equivalent.
```swift
// WRONG
func spaceshipDashboard<WarpDriveView: View, CaptainsLogView: View>(
warpDrive: WarpDriveView,
captainsLog: CaptainsLogView)
-> some View
{ … }
func generate<Planets>(_ planets: Planets) where Planets: Collection, Planets.Element == Planet {
…
}
// RIGHT
func spaceshipDashboard(
warpDrive: some View,
captainsLog: some View)
-> some View
{ … }
func generate(_ planets: some Collection<Planet>) {
…
}
```
We are adopting Swift 5.7 soon, so we should adopt guidance for its new language features.
Opaque generic parameter syntax is significantly less verbose and thus more legible than the full named generic parameter syntax. …

Add rule to prefer opaque generic parameter syntax

---

Package.swift

This PR bumps our SwiftFormat version to pull in [nicklockwood/SwiftFormat#1292](https://github.com/nicklockwood/SwiftFormat/pull/1292), which fixes a bug in the `opaqueGenericParameters` rule.

Bump SwiftFormat version

---

README.md

It is a best practice when writing assertion helpers to pass through the file and line from the caller's context. This ensures that errors surfaced by XCTest are most helpful. Here I update the code example in our style guide to follow that practice.
We strive to have our code examples follow known best practices.
@airbnb/swift-styleguide-maintainers

Update `prefer-opaque-generic-parameters` XCTest example to pass through `file` and `line` 

---

Package.swift

Our Swift Package Index badge in the README currently says this package supports Linux:
The package builds correctly on Linux, which is what SPI currently uses to detect platform compatibility. The plugin fails at runtime on Linux, though, because we have binary dependencies that only support macOS: https://github.com/airbnb/swift/discussions/197
The maintainer of Swift Package Index suggested this workaround (https://github.com/airbnb/swift/discussions/197#discussioncomment-4055303).

Update `Package.swift` to explicitly not support Linux

---

Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR proposes an update to the rule for long function declarations, to specify that effects (`async`, `throws`) should be written on the line after the closing paren:
```swift
// WRONG
func generateStars(
at location: Point,
count: Int,
color: StarColor,
withAverageDistance averageDistance: Float) async throws // these effects are easy to miss since they're visually associated with the last parameter
-> String 
{
populateUniverse()
}
// RIGHT
func generateStars(
at location: Point,
count: Int,
color: StarColor,
withAverageDistance averageDistance: Float) 
async throws -> String 
{
populateUniverse()
}
```
This can be auto-formatted using the SwiftFormat `--effectsposition wrap` option, added in https://github.com/nicklockwood/SwiftFormat/pull/1301.
1. Writing effects on the same line …

Update rule for long function declarations to specify effects (`async`, `throws`) should be written on the line after the closing paren

---

README.md

* Fixed the broken SE-0156 link which is due to a Markdown format typo.
* For doc readability.

Fix broken SE-0156 link

---

README.md

- Included a missing space after some comment delimiters. 😃 
- By the rule: [Include spaces or newlines before and after comment delimiters](https://github.com/airbnb/swift#whitespace-around-comment-delimiters)
cc. @calda

Include a missing space after some comment delimiters

---

README.md

- This PR proposes clarifying the rule [name unused function parameters as underscores](https://github.com/airbnb/swift#unused-function-parameter-naming) to be more specific and understandable way.
- Plus, adds the missing return type.
- In #136, calda said it was a 'real world' example, and I totally understand that, but the `Context` type is a bit ambiguous compared to other easy types used in this style guide. (like Universe, Galaxy, Planet, Star, etc.)
- so, I clarified this example with a more easy type, `Weather`.
- Open to suggestions on this, thanks! 😄 
cc. @calda

Clarify Rule: Name unused function parameters as underscores

---

README.md

This PR proposes clarifying the rule of "Never use the default case when switching over an enum" to be more specific.
I clarified rule with "real world" example and to follow clear and understandable examples that the guide is providing. (such as universe, weather and etc.)
Please review. Thanks! 😄
Reviewers
cc. @calda

Clarify Rule: Never use the default case when switching over an enum

---

README.md

This PR proposes to clarify comment of the "Use Swift's automatic enum values unless they map to an external source." 
1) I indicated whether the examples are wrong or right like other rules in the guide to increase readability.
2) The origin comment was not being specific as it only said "swiftformat:enable redundantRawValues" and "swiftformat:disable redundantRawValues". The heading of rule provides link to swiftformat, so I thought it was better to directly indicate that the examples are right for relying on Swift's automatic enum values.

Clarify Rule: Use Swift's automatic enum values unless they map to an external source.

---

README.md

This PR proposes to indicate `// WRONG` mark to the rule example.
As one of the rule example is not stating whether the example is right or wrong, it is confusing to understand the rule. Thus, I indicated that the example is wrong by following [Rule: Add a trailing comma on the last element of a multi-line array.](https://github.com/airbnb/swift#trailing-comma-array) to clarify the rule. 

Clarify Rule: Multi-line arrays should have each bracket on a separate line.

---

README.md

I adjusted two rules's wording, ``Use caseless `enum`s for organizing `public` or `internal` constants and functions into namespaces`` and ``Bind to `self` when upgrading from a weak reference``, to reduce confusion. 
``Bind to `self` when upgrading from a weak reference``'s example of wrongdoing contains `do work` key word which confuses if the example is right or wrong. ``Use caseless `enum`s for organizing `public` or `internal` constants and functions into namespaces`` was not stating if the case was wrong or right, so I thought adding `RIGHT` keyword increase readability of the example.

Clarify Rule: Use caseless enums for organizing public or internal constants and functions into namespaces.

---

Sources/AirbnbSwiftFormatTool/airbnb.swiftformat
Sources/AirbnbSwiftFormatTool/swiftlint.yml

I have added code to two source files excluding external libraries such as Carthage, Pods, and SourcePackages (SPM).
I added code to enforce the Airbnb style rules only on the code we wrote, as I believe it is the intended behavior to apply the rules only to our own code when using the command "swiftFormat .", which also modifies external libraries.

Update: ignore Rule OpenSource Library

---

Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR updates the `--swiftversion` in `airbnb.swiftformat` to Swift 5.8.
The Swift Package Plugin itself doesn't use this (it uses the Swift version specified in the `Package.swift` file), so I'm not sure we need to keep this around. Curious if anyone has any thoughts.
In the meantime while this is included in `airbnb.swiftformat`, we should keep it up to date.

Update SwiftFormat --swiftversion to 5.8

---

.github/actions/setup/action.yml
.github/workflows/main.yml

This PR updates CI to test multiple Xcode versions.
Currently we use the Xcode 12 runner, which defaults to Xcode 14.2 / Swift 5.7.
This PR additionally adds tests for Xcode 13.4.1 (Swift 5.6) and Xcode 14.3 (Swift 5.8).

Test multiple Xcode versions in CI

---

Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR proposes a new rule that protocol composition type aliases should be sorted alphabetically.
Autocorrect is implemented in the SwiftFormat `sortTypealiases` rule, added in https://github.com/nicklockwood/SwiftFormat/pull/1445.
```swift
// WRONG (not sorted)
public typealias Dependencies
= UniverseBuilderProviding
& LawsOfPhysicsProviding
& UniverseSimulatorServiceProviding
& PlanetBuilderProviding
& CivilizationServiceProviding
// RIGHT
public typealias Dependencies
= CivilizationServiceProviding
& LawsOfPhysicsProviding
& PlanetBuilderProviding
& UniverseBuilderProviding
& UniverseSimulatorServiceProviding
```
Type aliases are an unordered list with no natural ordering. Sorting alphabetically keeps these lists more organized, which is especially valuable for long protocol …

Add rule that protocol composition type aliases should be sorted alphabetically

---

Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR proposes a new rule that `else` statements should start on the same line as the previous condition's closing brace, unless the conditions are separated by a blank line or comments.
```swift
// WRONG
if let galaxy {
…
}
else if let bigBangService {
…
}
else {
…
}
// RIGHT
if let galaxy {
…
} else if let bigBangService {
…
} else {
…
}
// RIGHT, because there are comments between the conditions
if let galaxy {
…
}
// If the galaxy hasn't been created yet, create it using the big bang service
else if let bigBangService {
…
}
// If the big bang service doesn't exist, fail gracefully
else {
…
}
// RIGHT, because there are blank lines between the conditions
if let galaxy {
…
}
else if let bigBangService {
// If the galaxy hasn't been created yet, create it using the big bang service
…
} …
```

Add rule that else statements should start on the same line as previous closing brace

---

Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR proposes a new rule to add a linebreak before the else keyword in a multi-line guard statement.
```swift
// WRONG -- else should be on its own line for multi-line guard statements
guard
let galaxy,
galaxy.name == "Milky Way" else
{ … }
// WRONG -- else should be on the same line for single-line guard statements
guard let galaxy
else { … }
// RIGHT
guard
let galaxy,
galaxy.name == "Milky Way"
else { … }
// RIGHT
guard let galaxy else {
…
}
```
This was first suggested back in https://github.com/airbnb/swift/pull/108#issuecomment-715479492. This is also how the examples in the "wrap multi-line conditionals" rule description are formatted.
Placing the `else` on its own line makes it more visually distinct, and prevents it from blending in with the last statement.
We previously didn't …

Add rule to add a linebreak before the else keyword in a multi-line guard statement

---

README.md
Sources/AirbnbSwiftFormatTool/swiftlint.yml

Add lint rules to discourage the use of `#file` and `#filePath` literals (macros in 5.9). 
In addition, my editor removed some trailing whitespace - let me know if I should revert that. 
1. `#file`'s behavior is changing in future Swift versions (https://developer.apple.com/documentation/swift/file), from the problematic behavior of `#filePath` to the more ideal behavior of `#fileID`. We should just use the literal/macro with explicit and unchanging behavior. 
2. The documentation for `#filePath` says "Because #fileID doesn’t embed the full path to the source file, unlike #filePath, it gives you better privacy and reduces the size of the compiled binary. Avoid using #filePath outside of tests, build scripts, or other code that doesn’t become part of the shipping program." …

Add rules to discourage #file and #filePath

---

README.md

Swift 5.9 adds support for `package`-level declarations ([SE-0386](https://github.com/apple/swift-evolution/blob/main/proposals/0386-package-access-modifier.md)). We should mention this in the rule discussing how to organize declarations.
Should we merge this now or wait until Swift 5.9 is released? Either seems ok to me

Add `package` keyword to list of declaration categories

---

Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR proposes a new rule to omit the `internal` keyword from declarations with internal access control.
Autocorrect is implemented in the new `redundantInternal` SwiftFormat rule, which was added in https://github.com/nicklockwood/SwiftFormat/pull/1486.
```swift
// WRONG
internal class Spaceship {
internal init() { … }
internal func travel(to planet: Planet) { … }
}
// RIGHT, because internal access control is implied if no other access control level is specified.
class Spaceship {
init() { … }
func travel(to planet: Planet) { … }
}
```
Internal access control is implied for declarations without an explicit access control level, so the `internal` keyword is redundant.

Add rule to omit `internal` keyword from declarations with internal access control

---

Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR proposes a new rule to prefer using for loops over the functional `forEach { ... }` method, unless using `forEach` as the last element in a functional chain.
Autocorrect is implemented in the new `forLoop` SwiftFormat rule, which was added in https://github.com/nicklockwood/SwiftFormat/pull/1490.
```swift
// WRONG
planets.forEach { planet in
planet.terraform()
}
// WRONG
planets.forEach {
$0.terraform()
}
// RIGHT
for planet in planets {
planet.terraform()
}
// ALSO FINE, since forEach is useful when paired with other functional methods in a chain.
planets
.filter { !$0.isGasGiant }
.map { PlanetTerraformer(planet: $0) }
.forEach { $0.terraform() }
```
For loops are more idiomatic than the `forEach` method, and are typically familiar to all developers who have experience with …

Add rule to prefer for loops over functional `forEach { ... }` method

---

Plugins/FormatSwift/Plugin.swift

The Airbnb Swift Format Tool currently infers a package's minimum Swift supported version by taking the `// swift-tools-version` from the `Package.swift` (e.g. `// swift-tools-version:5.6`).
A project can also have multiple `Package.swift`s with different tools versions. This is required if a package wants to make use of functionality that is only available in later tools versions, without dropping support for earlier tool versions. For example, you can use `// swift-tools-version:5.8` in your `Package.swift` and have an additional `Package@swift-5.7.swift` with `// swift-tools-version:5.7`.
This PR updates the AirbnbSwift Format Tool to take into account all of these versions, and use the lowest value as the minimum Swift version when running the code formatter.

Include version-specific package manifests when determining default minimum Swift version

---

Package.swift
Sources/AirbnbSwiftFormatTool/AirbnbSwiftFormatTool.swift

I noticed we were using an outdated version of SwiftLint in this repo. We are currently using SwiftLint 0.52.1 within Airbnb.
This PR updates this repo to also use SwiftLint 0.52.1.

Update to SwiftLint 0.52.1

---

README.md
Sources/AirbnbSwiftFormatTool/swiftlint.yml

This PR proposes a new rule to prefer avoiding usage of `@unchecked Sendable`. Instead, we should use a standard `Sendable` conformance instead where possible. If working with a type from a module that has not yet been updated to support Swift Concurrency, suppress concurrency-related errors using `@preconcurrency import`. 
`@unchecked Sendable` provides no guarantees about the thread safety of a type, and instead unsafely suppresses compiler errors related to concurrency checking. 
There are typically other, safer methods for suppressing concurrency-related errors:
A `Sendable` conformance is the preferred way to declare that a type is thread-safe. The compiler will emit an error if a type conforming to `Sendable` is not thread-safe. For example, simple value types and immutable classes …

Add rule to avoid using `@unchecked Sendable`

---

README.md
Sources/AirbnbSwiftFormatTool/swiftlint.yml

This PR proposes a new rule to prefer using `weak` captures over `unowned` captures.
`unowned` captures are unsafe because they will cause the application to crash if the referenced object has been deallocated. `weak` captures are safer because they require the author to explicitly consider and handle the case where the referenced object no longer exists.
```swift
// WRONG: Crashes if `planet` has been deallocated when the closure is called.
spaceship.travel(to: planet, onArrival: { [unowned planet] in
planet.colonize()
})
spaceship.travel(to: planet, nextDestination: { [unowned planet] in
planet.moons.first ?? planet.sun
})
```
```swift
// RIGHT: Explicitly handles case where `planet` has been deallocated.
spaceship.travel(to: planet, onArrival: { [weak planet] in
guard let planet else { …
```

Add rule to prefer weak captures over unowned captures

---

README.md

This PR improves the discussion and examples for the "avoid `unowned` self" rule:
- The examples now use `unowned self` and `weak self`, which feels less contrived than the previous examples
- We now include discussion around explicitly capturing the instance members used in the closure (e.g. `[planet]` instead of `[weak self]` / `self?.planet`). 
----
`unowned` captures are unsafe because they will cause the application to crash if the referenced object has been deallocated.
```swift
// WRONG: Crashes if `self` has been deallocated when closures are called.
final class SpaceshipNavigationService {
let spaceship: Spaceship
let planet: Planet
func colonizePlanet() {
spaceship.travel(to: planet, onArrival: { [unowned self] in
planet.colonize()
})
}
func exploreSystem() { …
```

Improve discussion and examples for rule to avoid unowned captures

---

.github/workflows/main.yml
Package.swift
README.md
Sources/AirbnbSwiftFormatTool/AirbnbSwiftFormatTool.swift
Sources/AirbnbSwiftFormatTool/Command.swift
Tests/AirbnbSwiftFormatToolTests/AirbnbSwiftFormatToolTests.swift

This PR fixes an issue where the package plugin wouldn't run any of the SwiftLint lint-only rules unless we passed in the `--lint` flag (e.g. `swift format format --lint`).
That is, running `swift package format` would only run the SwiftLint rules that included autocorrect, but wouldn't run any of the SwiftLint rules lacking autocorrect.
For SwiftLint to apply autocorrection, you have to pass in the `--fix` flag, but that causes SwiftFormat to not run any of the lint-only rules. As a fix we _always_ run SwiftLint in lint-only mode (without `--fix`) and then additionally run it in autocorrect mode (with `--fix`) if there were lint errors that need to be corrected.
This PR also adds unit tests for the `AirbnbSwiftFormatTool` type, testing its behavior in response to receiving various exit …

Fix issue where package plugin wouldn't run SwiftLint lint-only rules unless passing in `--lint` flag

---

Package.swift
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR updates this repo to SwiftFormat 0.53, which is the version we are using internally at Airbnb.

Update to SwiftFormat 0.53

---

README.md

We have a rule that suggests to avoid using the `default` case when switching over an enum.
This rule is worded pretty strongly ("never use the `default` case"), but lacks autocorrect or linting, so has no enforcement. I also think there are valid reasons to use the default case.
I think we should just soften the wording of this rule (not use strict wording like "never"), since it is still good advice overall.
Some alternatives we could consider:
1. Add a lint rule to enforce this rule
- This is too heavy-handed, because there are valid use cases for using `default`. The prose rule includes a set of exceptions where it can make sense to use `default`.
- This is infeasible, because a linter wouldn't know if we are switching over an enum or not. We may be switching over something that can't …

Soften wording for rule to avoid using default in switch statements

---

Package.swift
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR updates the default SwiftFormat `--swiftversion` to Swift 5.9, which is the Swift version we now use internally at Airbnb.

Update to Swift 5.9

---

README.md

Now that we use [Swift 5.9](https://github.com/airbnb/swift/pull/248), the existing omit-return rule now also applies to functions / properties that have single-expression if/switch statements. Let's add some examples using this syntax to make it explicit that this existing rule applies to those cases. This is also potentially good educational content for anyone who doesn't know that this is permitted now.

Update omit-return rule discussion to include examples using if/swift expressions

---

Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

The default value of the `--shortoptionals` rule was changed from `always` to `except-properties` in https://github.com/nicklockwood/SwiftFormat/commit/5ec0a9413c7a2f22901ab9008fec7620cc75d14f. 
In anticipation of this change, let's explicitly list the `--shortoptionals always` option. This preserves the existing behavior of the `typeSugar` rule.

Specify `--shortoptionals always` option explicitly since default was updated to `except-properties`

---

Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

When running `swift package format`, we get this deprecation warning about the `sortedImports` rule:
> warning: sortedImports rule is deprecated. Use sortImports instead.
This PR removes the deprecated `sortedImports` rule in favor of the `sortImports` rule which replaces it.

Use `sortImports` rule instead of deprecated `sortedImports` rule

---

Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR proposes a new rule to add a line break after the assignment operator before a multi-line `if` or `switch` expression.
Autocorrection for this rule is implemented in the `wrapMultilineConditionalAssignment` SwiftFormat rule, added in https://github.com/nicklockwood/SwiftFormat/pull/1574.
This makes it so that `if` and `switch` expressions always have the same "shape" as standard `if` and `switch` statements, where:
1. The `if` / `switch` keyword is always the left-most token on a dedicated line of code
2. The conditional branches are always to the right of and below the `if` / `switch` keyword.
This is most consistent with the formatting of `if` / `switch` statements in other contexts, and thus makes it easier to recognize that the code is using an `if` or `switch` expression at a …

Add rule to add a line break after the assignment operator before a multi-line `if` or `switch` expressions

---

Plugins/FormatSwift/Plugin.swift
Sources/AirbnbSwiftFormatTool/AirbnbSwiftFormatTool.swift

They were not critical errors, but I corrected a few typos.
1. `swiftversion` was not written in lowerCamelCase.
2. Letter `r` was missing in `AibnbSwiftFormatTool`

Fix typos in log

---

README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR proposes a new rule to avoid using semicolons.
Semicolons are not required at the end of a line, so should be omitted. While you can use semicolons to place two statements on the same line, it is more common and preferred to separate them using a newline instead.
```swift
/// WRONG. Semicolons are not required and can be omitted.
let mercury = planets[0];
let venus = planets[1];
let earth = planets[2];
// WRONG. While you can use semicolons to place multiple statements on a single line,
// it is more common and preferred to separate them using newlines instead.
let mercury = planets[0]; let venus = planets[1]; let earth = planets[2];
// RIGHT
let mercury = planets[0]
let venus = planets[1]
let earth = planets[2]
// WRONG
guard let moon = planet.moon else { completion(nil); return …
```

Add rule to avoid using semicolons

---

README.md

This PR fixes the markdown formatting of the else-on-same-line rule, which was missing the closing `**`.

Fix markdown formatting of else-on-same-line rule

---

Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR proposes a new rule to insert a blank line following a switch case with a multi-line body:
> **Insert a blank line following a switch case with a multi-line body.** Spacing within an individual switch statement should be consistent. If any case has a multi-line body then all cases should include a trailing blank line. The last switch case doesn't need a blank line, since it is already followed by a closing brace.
Autocorrect is implemented in the `blankLineAfterMultilineSwitchCase` and `consistentSwitchStatementSpacing` SwiftFormat rules, which were added in https://github.com/nicklockwood/SwiftFormat/pull/1621.
Like with [declarations in a file](https://github.com/airbnb/swift#newline-between-scope-siblings), inserting a blank line between scopes makes them easier to visually …

Add rule to insert a blank line following a switch case with a multi-line body

---

README.md

- This PR corrects indentation inconsistencies in `switch case with a multi-line body`.
- By the basic rule itself. :) "Use 2 spaces to indent lines."

Correct indentation in multi-line switch case

---

Package.swift
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

Within Airbnb, we now use Swift 5.10 and SwiftFormat 0.54-beta-4

Update Swift version and SwiftFormat build

---

Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

_Please react with 👍/👎 below if you agree or disagree with this proposal._
This PR proposes a new rule to use doc comments (`///`) instead of regular comments (`//`) before declarations within type bodies or at the top level.
```swift
// WRONG
// A planet that exists somewhere in the universe.
class Planet {
// Data about the composition and density of the planet's atmosphere if present.
var atmosphere: Atmosphere?
// Data about the size, location, and composition of large bodies of water on the planet's surface.
var oceans: [Ocean]
// Terraforms the planet, by adding an atmosphere and ocean that is hospitable for life.
func terraform() {
// This gas composition has a pretty good track record so far!
let composition = AtmosphereComposition(nitrogen: 0.78, oxygen: 0.22)
// Generate the …
```

Add rule to use doc comments before declarations

---

README.md

We realized that the "Platforms: macOS" banner at the top of the README is potentially confusing.
These Swift Package Index banners refer to the Swift versions and platforms supported by our Swift package plugin. However, without this context it may look like this is saying that the Style Guide primarily supports macOS.
I still like the Swift versions banner, so think that's worth keeping. This has the side effect of suggesting that the style guide itself "supports" the given range of Swift versions, which is true.
@airbnb/swift-styleguide-maintainers

Remove "Platforms: macOS" supported platforms banner

---

Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

_Please react with 👍/👎 below if you agree or disagree with this proposal._
This PR proposes a new rule to prefer letting the type of a property be inferred from the right-hand-side value rather than writing the type explicitly on the left-hand side:
```swift
// WRONG
let sun: Star = .init(mass: 1.989e30)
let earth: Planet = .earth
// RIGHT
let sun = Star(mass: 1.989e30)
let earth = Planet.earth
```
Autocorrect support for this rule is implemented in https://github.com/nicklockwood/SwiftFormat/pull/1640.
We already have a rule to omit redundant types. It converts `let sun: Star = Star()` to `let sun = Star()`, rather than to `let sun: Star = .init()`.
The syntax with inferred types is more idiomatic, and is much more common, than the syntax with explicit types.
I briefly checked the …

Add rule to infer property types from the right-hand-side value rather than writing the type explicitly on the left-hand side

---

.github/actions/setup/action.yml
.github/workflows/main.yml
Gemfile
Gemfile.lock
Rakefile

This PR adds a `bundle exec rake update:swiftformat` command that updates the SwiftFormat dependency `Package.swift` to reference the most recent version published in the https://github.com/calda/SwiftFormat repo.
This combines nicely with https://github.com/nicklockwood/SwiftFormat/pull/1721, which automates the creation of the artifact bundle.
If you run this right now, the command applies this change to the `Package.swift` file:
```diff
diff --git a/Package.swift b/Package.swift
index 579c10c..7b2daee 100644
--- a/Package.swift
+++ b/Package.swift
@@ -42,8 +42,8 @@ let package = Package(
.binaryTarget(
name: "SwiftFormat",
-      url: "https://github.com/calda/SwiftFormat/releases/download/0.54-beta-7/SwiftFormat.artifactbundle.zip",
-      checksum: …
```

Add command to update SwiftFormat reference to latest version

---

Package.swift
Rakefile
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

Updating to [0.55-beta-2](https://github.com/calda/SwiftFormat/releases/tag/0.55-beta-2). 
Also updated two breaking rule name changes in [airbnb.swiftformat](https://github.com/airbnb/swift/compare/manny-lopez--update-swiftformat-version?expand=1#diff-18c32716db8d9f80bf3ceeeba1eb9c57a8557a085a1e632d06e0738710b81af1) 
```diff
- --rules blankLineAfterMultilineSwitchCase
- --rules consistentSwitchStatementSpacing
+ --rules blankLineAfterSwitchCase
+ --rules consistentSwitchCaseSpacing
```

Update SwiftFormat to v. 0.55-beta-2

---

README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR proposes a new rule to avoid defining properties that are then returned immediately. Instead, return the value directly.
Autocorrect support is implemented in the SwiftFormat `redundantProperty` rule, which as added in https://github.com/nicklockwood/SwiftFormat/pull/1654.
```swift
// WRONG
var spaceship: Spaceship {
let spaceship = spaceshipBuilder.build(warpDrive: warpDriveBuilder.build())
return spaceship
}
// RIGHT
var spaceship: Spaceship {
spaceshipBuilder.build(warpDrive: warpDriveBuilder.build())
}
// WRONG
var spaceship: Spaceship {
let warpDrive = warpDriveBuilder.build()
let spaceship = spaceshipBuilder.build(warpDrive: warpDrive)
return spaceship
}
// RIGHT
var spaceship: Spaceship {
let warpDrive = warpDriveBuilder.build()
return spaceshipBuilder.build(warpDrive: …
```

Add redundantProperty rule

---

PULL_REQUEST_TEMPLATE.md

This PR removes the `Please react with 👍/👎 if you agree or disagree with this proposal.` text from this repo's PR template.
We have moved proposal reviews from github.com to our internal Slack. While feedback is still welcome on the github.com pull request, we no longer need to specifically ask readers to react to the PR.
This should make it more clear that the internal poll is the source of truth for proposal reviews.

Remove "Please react with 👍/👎 if you agree or disagree with this proposal" text from PR template

---

Package.swift

This PR removes the `#error("Linux is currently not supported")` error from our Package.swift.
This was originally so Swift Package Index wouldn't list this package as supporting Linux. This is causing issues for folks though, since it prevents the Package.manifest from being parsed on Linux: https://github.com/airbnb/swift/discussions/197#discussioncomment-9501585
Since we removed the Swift Package Index platforms badge from the README in https://github.com/airbnb/swift/pull/271, and this `#error` is causing issues for folks, it seems best to just remove it.

Remove Linux #error from Package.swift

---

Package.swift
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

As of https://github.com/nicklockwood/SwiftFormat/pull/1736, the `organizeDeclarations` rule is now fully configurable, and lets you specify the sort order of declarations. The default behavior of the `organizeDeclarations` is now different from the behavior defined in our style guide. To keep the behavior we want, we can provide our own configuration explicitly.
The corresponding configuration that matches our style guide is:
```
--visibilityorder beforeMarks,instanceLifecycle,open,public,package,internal,fileprivate,private # organizeDeclarations
--typeorder nestedType,staticProperty,staticPropertyWithBody,classPropertyWithBody,instanceProperty,instancePropertyWithBody,staticMethod,classMethod,instanceMethod # organizeDeclarations
```

Add explicit category ordering configuration for organizeDeclarations rule

---

Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR adds a new rule to place doc comments for a declaration before any attributes on the declaration.
```swift
// WRONG
@MainActor
/// A spacecraft with everything you need to explore the universe.
struct Spaceship { … }
// RIGHT
/// A spacecraft with everything you need to explore the universe.
@MainActor
struct Spaceship { … }
```
Autocorrect support is implemented in the SwiftFormat `docCommentsBeforeAttributes` rule, which was added in https://github.com/nicklockwood/SwiftFormat/pull/1766.
Placing the doc comment before any attributes is the most common practice, but I noticed some examples in our codebase where the doc comment is between the attributes and the rest of the declaration.
On the tooling side, Xcode correctly handles doc comments placed above attributes (see how the …

Add rule to place doc comments before any attributes

---

Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

After merging https://github.com/nicklockwood/SwiftFormat/pull/1747 and https://github.com/airbnb/swift/pull/280, this PR adds the SwiftUI property declaration ordering rule to the style guide.
SwiftUI Properties are a special type of property that lives inside SwiftUI views. These views conform to the `DynamicProperty` protocol and cause the a view's body to re-compute. Given this common functionality and also a similar syntax, it is preferred to group them together. 
```swift
// WRONG
struct CustomSlider: View {
// MARK: Internal
var body: some View {
...
}
// MARK: Private
@Binding private var value: Value
private let range: ClosedRange<Double>
@Environment(\.sliderStyle) private var style
private let step: Double.Stride
@Environment(\.layoutDirection) private var layoutDirection
}
// …
```

Add SwiftUI Property declaration to sub section ordering list

---

README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR adds rule `emptyExtension` to remove empty extensions that define no properties, functions, or conformances.
```swift
// WRONG: The first extension is empty and redundant.
extension Planet {}
extension Planet: Equatable {}
// RIGHT: Empty extensions that add a protocol conformance aren't redundant.
extension Planet: Equatable {}
```
Improves readability since the code has no effect and should be removed for clarity.

Add emptyExtension rule

---

README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR adds rule `unusedPrivateDeclaration` to remove unused private and fileprivate properties, functions, and typealiases.
```swift
// WRONG: Includes private declarations that are unused
struct Planet {
var ageInBillionYears: Double {
ageInMillionYears / 1000
}
private var ageInMillionsOfYears: Double
private typealias Dependencies = UniverseBuilderProviding // unused
private var mass: Double // unused
private func distance(to: Planet) { } // unused
}
// RIGHT
struct Planet {
var ageInBillionsOfYears: Double {
ageInMillionYears / 1000
}
private var ageInMillionYears: Double
}
```
Improves readability since the code has no effect and should be removed for clarity.

Add unusedPrivateDeclaration rule

---

Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat
Sources/AirbnbSwiftFormatTool/swiftlint.yml

We are consolidating on using SwiftFormat for autocorrectable rules, and SwiftLint only for lint-only rules.
This PR replaces several autocorrectable SwiftLint rules with the corresponding SwiftFormat rule that implements the corresponding functionality.

Replace several autocorrectable SwiftLint rules with SwiftFormat rules

---

README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR proposals an update to the infix operator spacing rule, clarifying that we should omit the trailing space after operators in operator `func` implementations like `static func ==(lhs: T, rhs: T) -> Bool`
```swift
// WRONG
static func == (_ lhs: MyView, _ rhs: MyView) -> Bool {
lhs.id == rhs.id
}
// RIGHT
static func ==(_ lhs: MyView, _ rhs: MyView) -> Bool {
lhs.id == rhs.id
}
```
The existing wording of the rule implies that it applies in all cases. However, for operator definitions like this, omitting the space is more common.
In our codebase we have 540 examples of `func == (` and 709 examples of `func ==(`. All of the other custom operator definitions I found for other operators (`+`, `-`, `+=`, `!=`, `<`, `>`)  also omitted the trailing space.
This is also more consistent with …

Update infix operator spacing rule to clarify rule for operator definitions like `static func ==(lhs: T, rhs: T) -> Bool`

---

README.md
Sources/AirbnbSwiftFormatTool/swiftlint.yml

This PR proposes updating the existing colon-spacing rule to also apply to dictionary literals. Previously, it applied to all usage of commas _except_ dictionary literals.
```swift
// WRONG
let moons: [Planet : Moon] = [
mercury : [], 
venus : [], 
earth : [theMoon], 
mars : [phobos,deimos],
]
// RIGHT
let moons: [Planet: Moon] = [
mercury: [], 
venus: [], 
earth: [theMoon], 
mars: [phobos,deimos],
]
```
It is much more common to omit the space before colon in dictionary literals. This also makes the rule more consistent and general.
This will also let us replace the SwiftLint `colon` rule with the SwiftFormat `spaceAroundOperators` rule. The SwiftLint rule has a `apply_to_dictionaries: false` option to exclude dictionary literals, but the SwiftFormat rule currently does not.

Update colon spacing rule to apply to dictionary literals

---

README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat
Sources/AirbnbSwiftFormatTool/swiftlint.yml

This PR replaces the SwiftLint `void_return` in favor to the SwiftFormat `void` rule in conjunction with the existing `redundantVoidReturnType` which cover the same functionality and additional rules described in the PR.
This is an effort to migrate all autocorrect rules to SwiftFormat

Add SwiftFormat void rule

---

Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR adds the SwiftUI property declaration sort rule to the style guide.
its preferred that SwiftUI properties are sorted by their dynamic property type. The order is determined by the first time a type appears:
```swift
// WRONG
struct CustomSlider: View {
@Binding private var value: Value
@State private var foo = Foo()
@Environment(\.sliderStyle) private var style
@State private var bar = Bar()
@Environment(\.layoutDirection) private var layoutDirection
private let range: ClosedRange<Double>
private let step: Double.Stride
}
// RIGHT
struct CustomSlider: View {
@Binding private var value: Value
@State private var foo = Foo()
@State private var bar = Bar()
@Environment(\.sliderStyle) private var style
@Environment(\.layoutDirection) private var layoutDirection
private let range: …
```

Add SwiftUI properties sort

---

README.md

- Replace SwiftLint void rule badge in favor to SwiftFormat badge
- Migrate alls SwiftFormat links to use main instead of master branch

Remove reference to SwiftLint Void rule

---

Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR adds a new rule to prefer using a generated EnvironmentValues property implementation.
This rule is implemented by the new `environmentEntry` SwiftFormat rule added in https://github.com/nicklockwood/SwiftFormat/pull/1908.
```swift
/// WRONG: The `EnvironmentValues` property depends on `IsSelectedEnvironmentKey`
struct IsSelectedEnvironmentKey: EnvironmentKey {
static var defaultValue: Bool { false }
}
extension EnvironmentValues {
var isSelected: Bool {
get { self[IsSelectedEnvironmentKey.self] }
set { self[IsSelectedEnvironmentKey.self] = newValue }
}
}
/// RIGHT: The `EnvironmentValues` property uses the @Entry macro 
extension EnvironmentValues {
@Entry var isSelected: Bool = false
}
```
Manually-implemented environment keys are verbose and it is considered a legacy pattern. …

Add rule to prefer a generated EnvironmentValue property implementation when possible

---

.github/workflows/main.yml
Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

SwiftFormat 0.55 was recently released. This PR updates our build to 0.56-beta-1, which is based off of 0.55.3.
Several rules that were previously only available on `develop` were released officially in 0.55.0. As a part of this some of the rule and option names were updated.

Update to SwiftFormat 0.56-beta-1 based on 0.55 release

---

Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR proposes a new rule to prefer using `count(where: { ... })` over `filter { ... }.count`.
```swift
// WRONG
let planetsWithMoons = planets.filter { !$0.moons.isEmpty }.count
// RIGHT
let planetsWithMoons = planets.count(where: { !$0.moons.isEmpty })
```
Autocorrect is implemented in https://github.com/nicklockwood/SwiftFormat/pull/1939.
Swift 6.0 ([finally!](https://forums.swift.org/t/accepted-again-se-0220-count-where/66659)) added a `count(where:)` method to the standard library.

Add rule to prefer `count(where: { ... })` over `filter { ... }.count`

---

Sources/AirbnbSwiftFormatTool/swiftlint.yml

This PR updates the `no_release_standard_out` lint rule to include the SwiftUI `_printChanges` helper.
Currently there's nothing stopping you from calling this in code merged to master.

 Update `no_release_standard_out` lint rule to include SwiftUI `_printChanges` helper

---

Package.swift

This PR updates the SwiftFormat binary to 0.56 beta 6, which is the version we are using at Airbnb.

Update SwiftFormat to 0.56 beta 6

---

Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR proposes a new rule to avoid prefixing Swift Testing test case methods with a "`test`" prefix. Autocorrect is implemented in the `swiftTestingTestCaseNames` SwiftFormat rule ([nicklockwood/SwiftFormat#1979](https://github.com/nicklockwood/SwiftFormat/pull/1979#issuecomment-2667272951)).
```swift
import Testing
/// WRONG
struct SpaceshipTests {
@Test
func testWarpDriveEnablesFTLTravel() { ... }
@Test
func testArtificialGravityMatchesEarthGravity() { ... }
}
/// RIGHT
struct SpaceshipTests {
@Test
func warpDriveEnablesFTLTravel() { ... }
@Test
func artificialGravityMatchesEarthGravity() { ... }
}
```
Prefixing test case methods with "`test`" was necessary with XCTest, but is not necessary in Swift Testing. [Idiomatic usage](https://developer.apple.com/documentation/testing/migratingf …

Add rule to avoid prefixing Swift Testing test case methods with "test"

---

Package.swift

This PR updates SwiftFormat to `0.56-beta-9`, which is the version we are now using at Airbnb.

Update to SwiftFormat 0.56-beta-9

---

Package.swift
Rakefile

To simplify the process of adopting prerelease SwiftFormat builds, I set up a new nightly build pipeline in [calda/SwiftFormat-nightly](https://github.com/calda/SwiftFormat-nightly).
This PR updates `bundle exec rake update:swiftformat` to use the latest nightly build from that repo.
To confirm that works this PR also updates to the current nightly build.

Update `update:swiftformat` to use nightly builds from `calda/SwiftFormat-nightly` repo

---

Package.swift
Plugins/FormatSwift/Plugin.swift
README.md
Sources/AirbnbSwiftFormatTool/AirbnbSwiftFormatTool.swift
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat
Tests/AirbnbSwiftFormatToolTests/AirbnbSwiftFormatToolTests.swift

This PR updates our Swift formatting rules to enable `callsiteparen = balanced`, which ensures consistent placement of parentheses and arguments in multiline function **calls**. With this option, the opening and closing parentheses are always balanced across lines, improving readability and making edits and diffs more predictable. It also works seamlessly with trailing commas to simplify future changes.
---
Currently, multiline function calls can inconsistently close the parenthesis on the same line as the last argument:
```swift
let result = executeRequest(
request,
onSuccess: { ... },
onFailure: { ... })
```
With `callsiteparen = balanced`, this becomes:
```swift
let result = executeRequest(
request,
onSuccess: { ... },
onFailure: { ... }
)
```
- **Predictable structure**  
The closing …

Match call-site paren on multi-line function calls

---

Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR proposes a new rule to avoid `public` access control in `internal` types.
Autocorrect is implemented in the `redundantPublic` SwiftFormat rule, which was added in [nicklockwood/SwiftFormat#2075](https://github.com/nicklockwood/SwiftFormat/pull/2075).
In an `internal` type, any body declaration with a `public` modifier is actually `internal` -- the `public` modifier is redundant and has no effect.
```swift
// WRONG
class Spaceship {
public init() { … }
public func travel(to planet: Planet) { … }
}
// RIGHT
class Spaceship {
init() { … }
func travel(to planet: Planet) { … }
}
```

Add rule to avoid `public` access control in `internal` types

---

README.md

Fixes a typo in README - `EnvironemtnValues` -> `EnvironmentValues`.
I noticed it while reading our styleguide.

Fixes a typo in README

---

README.md

@jqsilver added a new "Testing" section to the style guide in https://github.com/airbnb/swift/pull/313.
This PR moves the existing "Swift Testing test case names" rule to the testing section.

Move "Swift Testing test case names" rule to new "Testing" section

---

Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR adds a new rule to only define a single property or enum case per line.
```swift
// WRONG
let mercury, venus: Planet
let earth = planets[2], mars = planets[3]
let (jupiter, saturn) = (planets[4], planets[5])
enum IceGiants {
case neptune, uranus
}
// RIGHT
let mercury: Planet
let venus: Planet
let earth = planets[2]
let mars = planets[3]
let jupiter = planets[4]
let saturn = planets[5]
enum IceGiants {
case neptune
case uranus
}
// ALSO RIGHT: Tuple destructing is fine for values like function call results.
let (ceres, pluto) = findAndClassifyDwarfPlanets()
```
- Declarations that define a single property are much more common, and more idiomatic.
- Only using the standard form of property declarations makes it easier to write and maintain tools that operate on source code, like …

Add rule to only define a single property or enum case per line

---

Package.swift
README.md
Sources/AirbnbSwiftFormatTool/airbnb.swiftformat

This PR enables autocorrect for the existing "prefer `final` classes" rule.
Autocorrect is implemented using the new `preferFinalClasses` SwiftFormat rule: https://github.com/nicklockwood/SwiftFormat/pull/2196

Add autocorrect for "prefer `final` classes" rule
